#!/bin/bash
# Replicated System Installer
# Generated by archgen

clear
OK="$(tput setaf 2)[OK]$(tput sgr0)"
ERROR="$(tput setaf 1)[ERROR]$(tput sgr0)"
NOTE="$(tput setaf 3)[NOTE]$(tput sgr0)"
INFO="$(tput setaf 4)[INFO]$(tput sgr0)"
RESET="$(tput sgr0)"

LOG="install.log"
echo "--- Installation started on $(date) ---" > "$LOG"

# Check if running as root
if [[ $EUID -eq 0 ]]; then
    echo "$ERROR This script should NOT be executed as root!! Exiting." | tee -a "$LOG"
    exit 1
fi

# Ensure whiptail is installed
if ! command -v whiptail >/dev/null; then
    echo "$NOTE whiptail is not installed. Installing libnewt..." | tee -a "$LOG"
    sudo pacman -S --noconfirm libnewt >> "$LOG" 2>&1
fi

whiptail --title "System Replicator Installer" \
    --msgbox "Welcome to your custom system replicator installer!\n\nThis installer will recreate your system packages and configurations from your harvested template." 12 70

# Menu Options
CHOICES=$(whiptail --title "Select Components to Install" --checklist \
    "Choose options to configure (Spacebar to select, Tab to finish):" 18 70 8 \
    "00-base" "Configure pacman and update system" "ON" \
    "01-aur" "Configure AUR Helper (yay/paru)" "ON" \
    "02-pkgs" "Install harvested official pacman packages" "ON" \
    "03-aur-pkgs" "Install harvested AUR packages" "ON" \
    "04-dots" "Deploy dotfiles, shell configs, and wallpapers" "ON" \
    "05-sddm" "Install and configure SDDM + theme" "OFF" \
    "06-themes" "Install custom GTK themes and icons" "OFF" \
    3>&1 1>&2 2>&3)

if [ $? -ne 0 ]; then
    echo "❌ Installation cancelled." | tee -a "$LOG"
    exit 0
fi

execute_script() {
    local script_name="install-scripts/$1.sh"
    if [ -f "$script_name" ]; then
        chmod +x "$script_name"
        echo "$INFO Running $1..." | tee -a "$LOG"
        ./"$script_name" 2>&1 | tee -a "$LOG"
        if [ ${PIPESTATUS[0]} -eq 0 ]; then
            echo "$OK Completed $1 successfully." | tee -a "$LOG"
        else
            echo "$ERROR Failed during $1 execution." | tee -a "$LOG"
            exit 1
        fi
    else
        echo "$ERROR Script $script_name not found!" | tee -a "$LOG"
    fi
}

for choice in $CHOICES; do
    choice=$(echo "$choice" | tr -d '"')
    case "$choice" in
        00-base) execute_script "00-base" ;;
        01-aur) execute_script "01-aur-helper" ;;
        02-pkgs) execute_script "02-packages" ;;
        03-aur-pkgs) execute_script "03-aur-packages" ;;
        04-dots) execute_script "04-dotfiles" ;;
        05-sddm) execute_script "05-sddm" ;;
        06-themes) execute_script "06-themes" ;;
    esac
done

whiptail --title "Installation Complete" \
    --msgbox "Replication completed successfully!\n\nIt is highly recommended to reboot your system." 12 70

while true; do
    read -p "[ACTION] Would you like to reboot now? (y/n): " yn
    case $yn in
        [Yy]* ) sudo systemctl reboot; break;;
        [Nn]* ) echo "Please reboot manually later."; break;;
        * ) echo "Please answer yes or no.";;
    esac
done
